name: Build buster image

permissions:
  packages: write

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
      - v[0-9]+.[0-9]+.[0-9]+-*

jobs:
  build:
    name: Build image
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        architecture:
          - "arm64"
          - "amd64"

    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Set env variables
        run: |
          echo "TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
          echo "IMAGE_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker buildx action
        uses: docker/setup-buildx-action@v1

      - name: Run Docker buildx
        run: |
          docker buildx build --platform linux/${{ matrix.architecture }} \
            --tag ghcr.io/${{ github.repository_owner }}/${IMAGE_NAME}:${TAG}-${{ matrix.architecture }}-buster-slim --output "type=registry" \
            --build-arg arch=${{ matrix.architecture }} \
            --build-arg version=${TAG} \
            --build-arg lnd_version=v0.14.1-beta \
            --file Dockerfile.buster \
            ./

  create-manifest:
    name: Create two-architecture manifest
    runs-on: ubuntu-20.04
    needs: build

    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Set env variables
        run: |
          echo "TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
          echo "IMAGE_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create final manifest
        run: ./create-manifest.sh "ghcr.io/${{ github.repository_owner }}/${IMAGE_NAME}" "${TAG}" "buster-slim"
